/*
-- Query: SELECT * FROM CALLE
-- Date: 2022-08-22 18:31
*/
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (451,'Abeto','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (452,'Acacias','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (453,'Aceite','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (454,'Adarve','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (455,'Aguabajo','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (456,'Aguayo','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (457,'Agustin Rivero','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (458,'Alamos','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (459,'Albaicin','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (460,'Albarrana (La)','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (461,'Alcarrachela (De La)','Avenida',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (462,'Alcazar','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (463,'Alfareros','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (464,'Alfares','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (465,'Alfonso Aragon Fofo','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (466,'Algeciras','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (467,'Alhambra','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (468,'Almendro','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (469,'Almenillas','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (470,'Almonas','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (471,'Alonso','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (472,'Alonso Fernandez Grajera','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (473,'Amadeo Vives','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (474,'Amapola','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (475,'Ancha','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (476,'Andalucia','Avenida',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (477,'Antequera','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (478,'Anton de Arjona','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (479,'Arabella','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (480,'Arahales','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (481,'Arco de Belen','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (482,'Armas','Plaza',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (483,'Arquillos','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (484,'Arrieros','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (485,'Arroyo','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (486,'Artesanos','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (487,'Avendaño','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (488,'Azacanes','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (489,'Azofaifo','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (490,'Bachiller','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (491,'Bañales','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (492,'Barba','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (493,'Barcelona','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (494,'Barquete','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (495,'Barrasa','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (496,'Barrera de San Gregorio','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (497,'Barrera Oñate','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (498,'Bartolome Jimenez Torres','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (499,'Bataneros','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (500,'Beatas','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (501,'Bellidos','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (502,'Beneficiados','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (503,'Berbisa','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (504,'Bermuda','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (505,'Bizco Pardal','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (506,'Boabdil','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (507,'Bodegas','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (508,'Cabriteros','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (509,'Cadenas','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (510,'Cadiz','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (511,'Calderon','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (512,'Caleros','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (513,'Calzada (La)','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (514,'Camilo Jose Cela','Plaza',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (515,'de La Fuensanta','Camino',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (516,'de Las Huertas','Camino',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (517,'Camino de Los Romeros','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (518,'Campana (La)','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (519,'Campanillas','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (520,'Cañada del Rosal','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (521,'Cañaveralejo','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (522,'Canovas del Castillo','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (523,'Capataz Gutierrez Tagua','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (524,'Capilla','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (525,'Carcel','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (526,'Carlos Cano (De)','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (527,'Carmelitas','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (528,'Carmen','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (529,'Carmona','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (530,'Carpinteros','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (531,'Carreras','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (532,'Palma del Rio','Carretera',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (533,'Cartuja (La)','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (534,'Castaño','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (535,'Castril','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (536,'Caus','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (537,'Cava','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (538,'Cavilla','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (539,'Cecilia','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (540,'Celestino Montero','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (541,'Celindas (Las)','Pasaje',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (542,'Cerro de La Concepcion','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (543,'Cerro de La Habana','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (544,'de La Polvora','Cerro',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (545,'Cesareo Cambronero','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (546,'Cespedes','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (547,'Cesteria','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (548,'Chopo','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (549,'Cinteria','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (550,'Cipres','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (551,'Circunvalacion (De)','Carretera',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (552,'Ciudad de Aranjuez','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (553,'de Las Torres','Ciudad',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (554,'Clara Campoamor','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (555,'Colon','Plaza',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (556,'Colonda','Barriada',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (557,'Comedias','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (558,'Compañia','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (559,'Compositor Juan Bermudo','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (560,'Concordia (De La)','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (561,'Conde','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (562,'Constitucion (De La)','Avenida',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (563,'Cordoba','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (564,'Cordobes','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (565,'Coronado','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (566,'Cristo de Confalon','Avenida',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (567,'Cronista Martin Jimenez','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (568,'Cuatro de Diciembre','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (569,'Curtidores','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (570,'Delgadillo','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (571,'Diamantino Garcia','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (572,'Doctor Benitez','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (573,'Doctor Fleming','Avenida',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (574,'Doctor Jimenez de Lorite','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (575,'Doctor Sanchez Malo','Avenida',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (576,'Doctrina','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (577,'Dolores Ibarruri','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (578,'Dos Pozos','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (579,'Drago','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (580,'Ebanistas','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (581,'Ebano','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (582,'Elvira','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (583,'Emigrantes (Los)','Avenida',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (584,'Emilio Castelar','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (585,'Emparedamiento','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (586,'Empedrada','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (587,'Encina','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (588,'Enrique El Gandinga','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (589,'Escritor Mas Y Laglera','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (590,'Eslava','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (591,'Espada','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (592,'España','Plaza',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (593,'Espiritu Santo','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (594,'Estatuto de Autonomia','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (595,'Estepa','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (596,'Eugenio D\'ors','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (597,'Europa (De)','Plaza',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (598,'Evaristo Espinosa','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (599,'Feria','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (600,'Fernandez Pintado','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (601,'Fernando Iii','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (602,'Fernando Labrada','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (603,'Ferrocarril (Del)','Avenida',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (604,'Ferrocarril (El)','Ronda',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (605,'Fiel','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (606,'Fisico','Camino',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (607,'Flores','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (608,'Forjadores','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (609,'Francia','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (610,'Francos','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (611,'Fray Agustin de Los Reyes','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (612,'Fray Juan Bermudo','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (613,'Fresno','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (614,'Fuensanta (La)','Barriada',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (615,'Fuente Nueva','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (616,'Fuentes de Andalucia','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (617,'Funcionarios 80 Viviendas','Barriada',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (618,'Gabriela Mistral','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (619,'Galindo','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (620,'Gameras','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (621,'Garay Y Conde','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (622,'Garci Sanchez','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (623,'Garcilaso','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (624,'Garcilopez','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (625,'General Weyler','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (626,'Generalife','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (627,'Genil (Del)','Avenida',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (628,'Giles Y Rubio','Plaza',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (629,'Girasoles (Los)','Urbanización',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (630,'Gonzalo','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (631,'Granada','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (632,'Guadalajara','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (633,'Guarnicioneros','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (634,'Guerra','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (635,'Guillermo Gutierrez','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (636,'Haya','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (637,'Henchideros','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (638,'Hernan Perez','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (639,'Herrera','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (640,'Hist Padre Martin Roa','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (641,'Horno','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (642,'Hospital','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (643,'Hospitalet','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (644,'Huelva','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (645,'Huertas (De Las)','Ronda',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (646,'Huerto','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (647,'Ignacio de Soto','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (648,'Ignacio Ellacuria','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (649,'Impresor Juan Los Reyes','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (650,'Isaac Albeniz','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (651,'Isaac Peral','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (652,'Isadora Duncan','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (653,'Italia','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (654,'Jaen','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (655,'Jaime Ostos','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (656,'Jeronimo de Aguilar','Avenida',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (657,'Jesus del Gran Poder','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (658,'Jesus Nazareno','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (659,'Jesus Sin Soga','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (660,'Joaquin Rodrigo','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (661,'Joaquin Turina','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (662,'John Lennon','Avenida',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (663,'Jorge Manrique','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (664,'Jose Canalejas','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (665,'Jovar','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (666,'Juan de Angulo','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (667,'Juan Diaz Custodio','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (668,'Juan Muñoz','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (669,'Juan Paez','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (670,'Juan Xxiii','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (671,'Julianes','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (672,'Jurado','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (673,'Lebrija','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (674,'Leonis','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (675,'Leonor','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (676,'Limero','Avenida',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (677,'Lopez','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (678,'Lorenzo Lucena','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (679,'Loza','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (680,'Lucas','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (681,'Luisiana','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (682,'Luna','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (683,'Luque','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (684,'Maestre','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (685,'Malaga','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (686,'Malaliño','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (687,'Mandoble','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (688,'Manuel de Falla','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (689,'Manuel Ostos Y Ostos','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (690,'Manuel Romero Nieto','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (691,'Marchena','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (692,'Margarita Xirgu','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (693,'Maria Auxiliadora','Avenida',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (694,'Maria Curie','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (695,'Maria de La O Lejarraga','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (696,'Maria Guerrero','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (697,'Maria Zambrano','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (698,'Mariana Pineda','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (699,'Maritorija','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (700,'Marmoles','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (701,'Marquesa (La)','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (702,'Mas Y Prat','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (703,'Matadero','Plaza',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (704,'Mayor','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (705,'Mendoza','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (706,'Merced','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (707,'Merinos','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (708,'Mezquita','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (709,'Miguel de Cervantes','Avenida',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (710,'Milagrosa (La)','Pasaje',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (711,'Minarete','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (712,'Miragenil','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (713,'Molinos (De Los)','Ronda',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (714,'Moreria','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (715,'Mortecina','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (716,'Mostaceros','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (717,'Mujeres Jornaleras','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (718,'Najeras','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (719,'Naranjillos','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (720,'Nardo','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (721,'Navajas','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (722,'Nogal','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (723,'Norias (Las)','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (724,'Ntra Sra de Los Dolores','Plaza',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (725,'Nuestra Señora del Valle','Plaza',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (726,'Nuestra Señora del Valle','Avenida',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (727,'Nueva','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (728,'Nueva Andalucia','Barriada',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (729,'Olivares','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (730,'Olmo','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (731,'Opera (De La)','Plaza',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (732,'Ostos','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (733,'Pacheco','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (734,'Padilla','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (735,'Palmeras (Las)','Urbanización',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (736,'Palo Santo','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (737,'Paloma','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (738,'Palomar','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (739,'Panaderos','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (740,'Paraiso','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (741,'Pardillo','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (742,'Pardo','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (743,'Parralejos','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (744,'Parteras','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (745,'Paz (De La)','Ronda',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (746,'Paz (La)','Barriada',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (747,'Pedregosa','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (748,'Pensamiento','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (749,'Pepe Luis Vargas','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (750,'Pepita Tomas','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (751,'Perdiz','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (752,'Peso','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (753,'Petra Kelly','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (754,'Picadero Bajo','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (755,'Picador','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (756,'Pilar Miro','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (757,'Pilarejo','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (758,'Pinichi','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (759,'Pino','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (760,'Pintor Fernando Briones','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (761,'Pinzapo','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (762,'Pio Xii','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (763,'Plateria','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (764,'Plaza de Toros','Avenida',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (765,'Poeta Balmaseda Gonzalez','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (766,'Poeta Manolo Mora','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (767,'Poligono Ind El Limero','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (768,'Portugal','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (769,'Pozo','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (770,'Profesor Collantes Teran','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (771,'Profesor Hernandez Diaz','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (772,'Profesor Sancho Corbacho','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (773,'Pueblo Saharaui','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (774,'Puente','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (775,'Puerta Cerrada','Plaza',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (776,'Puerta Nueva','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (777,'Puerta Osuna','Plaza',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (778,'Pulgosa','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (779,'Quintana','Plaza',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (780,'Rafael Maria Aguilar','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (781,'Ramon Y Cajal','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (782,'Ramos','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (783,'Recogidas','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (784,'Regidor','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (785,'Reina','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (786,'Rejano','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (787,'Rejas (Las)','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (788,'Rejon','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (789,'Reloj','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (790,'Residencial Astigi','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (791,'Residencial Confalon','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (792,'Rigoberta Menchu','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (793,'Rinconada','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (794,'Rio','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (795,'Rio Blanco','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (796,'Rio Cabra','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (797,'Roble','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (798,'Rocio','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (799,'Rodriguez Marin','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (800,'Rojas','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (801,'Ronda San Agustin','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (802,'Rosales','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (803,'Rosario','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (804,'Rueda','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (805,'Ruimartin','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (806,'Sacromonte','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (807,'Salas','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (808,'Saltadero','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (809,'Salto','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (810,'San Antonio','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (811,'San Bartolome','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (812,'San Benito','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (813,'San Cristobal','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (814,'San Francisco de Écija','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (815,'San Fulgencio','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (816,'San Gil','Plaza',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (817,'San Gregorio','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (818,'San Juan','Plaza',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (819,'San Juan Bosco','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (820,'San Marcos','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (821,'San Pablo','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (822,'Santa Ana','Barriada',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (823,'Santa Angela de La Cruz','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (824,'Santa Beatriz de Silva','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (825,'Santa Brigida','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (826,'Santa Catalina','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (827,'Santa Cruz','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (828,'Santa Florentina','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (829,'Santa Ines','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (830,'Santa Irene','Plaza',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (831,'Santa Maria','Plaza',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (832,'Santiago','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (833,'Domingo','Santo',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (834,'Sauce','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (835,'Secretario Armesto','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (836,'Severo Ochoa','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (837,'Sevilla','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (838,'Sol','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (839,'Soledad','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (840,'Sor Candida Sainz Alonso','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (841,'Soria','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (842,'Sumidero','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (843,'Tarancon','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (844,'Tello','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (845,'Teresa de Calcuta','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (846,'Tolerancia','Plaza',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (847,'Tolerancia (De La)','Plaza',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (848,'Tomas Bevia','Avenida',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (849,'Torcal','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (850,'Toreros (Los)','Avenida',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (851,'Toros','Plaza',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (852,'Torres Quevedo','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (853,'Tortola','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (854,'Trascampanario','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (855,'Tres Cruces','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (856,'Useras','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (857,'Vacas','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (858,'Valderrama','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (859,'Valle (Del)','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (860,'Vega','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (861,'Velez de Guevara','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (862,'Velez de Guevara','Plaza',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (863,'Ventorrillo','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (864,'Vicente Alexandre','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (865,'Victoria (La)','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (866,'Victoria Kent','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (867,'Victoriano Valpuesta','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (868,'Vidal','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (869,'Villa de Madrid','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (870,'Villa Pavillon Sous Bois','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (871,'Villalatas','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (872,'Villarreal','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (873,'Villates','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (874,'Violetas','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (875,'Virgen de La Piedad','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (876,'Virgen de Soterraño','Pasaje',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (877,'Virgen del Rocio','Pasaje',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (878,'Virgenes','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (879,'Yepes','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (880,'Zamorano','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (881,'Zapateros','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (882,'Zarzuela','Plaza',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (883,'Zayas','Calle',3);
INSERT INTO CALLE (`id`,`nombre`,`tipo`,`municipio_id`) VALUES (884,'Zurcideras','Calle',3);
