-- Creación de las tablas maestras
use poh;

INSERT INTO PAIS (ID, NOMBRE) VALUES (1, 'ESPAÑA');

INSERT INTO PROVINCIA (ID, NOMBRE, PAIS_ID) VALUES (2, 'SEVILLA', 1);

INSERT INTO MUNICIPIO (ID, NOMBRE, PROVINCIA_ID) VALUES (3, 'ECIJA',  2);

INSERT INTO CALLE (ID, MUNICIPIO_ID, TIPO, NOMBRE) VALUES (4, 3, 'CALLE', 'SALTO');
INSERT INTO CALLE (ID, MUNICIPIO_ID, TIPO, NOMBRE) VALUES (5, 3, 'AVENIDA', 'DE LOS EMIGRANTES');
INSERT INTO CALLE (ID, MUNICIPIO_ID, TIPO, NOMBRE) VALUES (6, 3, 'RONDA',  'DEL FERROCARRIL');

INSERT INTO IDENTIFICACION (ID, CODIGO_TARJETA, NOMBRE_TARJETA) VALUES (22, 0, 'MENOR DE EDAD');
INSERT INTO IDENTIFICACION (ID, CODIGO_TARJETA, NOMBRE_TARJETA) VALUES (23, 1, 'NIF');
INSERT INTO IDENTIFICACION (ID, CODIGO_TARJETA, NOMBRE_TARJETA) VALUES (24,  2, 'TARJETA DE EXTRANJERÍA');